Translate `hydration.md`
vuejs-fr/vue-ssr-docs pull request #10
Opened 2017-06-02 13:05 UTC by Haeresis

Relecture de cette traduction rapide.

2017-06-02 17:53 UTC, Kocal requested changes
Pas grand chose à corriger :open_mouth:

2017-06-02 17:53 UTC, Kocal commented on en/hydration.md
> +Parceque le serveur a déjà fait le rendu des balises, nous ne voulons évidemment pas tout jeter et recréer l'intégralité des éléments du DOM. À la place, nous voulons « hydrater » les balises statiqu
> les rendre

2017-06-03 09:09 UTC, Haeresis commented
Bon pour celui là @Kocal :) Merci à toi

2017-06-03 17:18 UTC, Kocal approved these changes

2017-06-05 07:36 UTC, merged