Traduction de `css.md`
vuejs-fr/vue-ssr-docs pull request #14
Opened 2017-06-19 11:42 UTC by Haeresis

Bon à review !

2017-06-20 06:55 UTC, Kocal requested changes
Une petite modif à apporter et c'est bon !

2017-06-20 06:55 UTC, Kocal commented on en/css.md
> +  S'il est utilisé pendant le rendu côté serveur, un composant CSS peut être récupéré et injecté dans la source HTML (automatiquement injecté avec l'option `template`). Côté client, quand le composan
> automatiquement injectée 

Puisqu'on parle de `la source HTML`

2017-06-22 08:25 UTC, Haeresis commented on en/css.md
> +  S'il est utilisé pendant le rendu côté serveur, un composant CSS peut être récupéré et injecté dans la source HTML (automatiquement injecté avec l'option `template`). Côté client, quand le composan
Non je ne crois pas. C'est bien le composant CSS (c.-à-d. la partie `<style></style>` de `.vue`) qui est injecté. J'ai traduit par « automatiquement injecté » alors que l'original disait « automatiquement géré » car c'est « l'injection qui est automatiquement gérée » et que ça revient au même. Mais je vais mettre « automatiquement pris en charge ».

EDIT : Ahhh, j'avais mis injecté pour conserver la même nomonclature que la phrase d'après qui dit plus « pris en charge » mais « injecté ».

2017-06-28 07:44 UTC, Haeresis commented
@Kocal. Bon pour toi ?

2017-06-28 09:14 UTC, Kocal approved these changes

2017-06-28 09:14 UTC, Kocal commented
Ouaip, j'avais rien trouvé d'autre à corriger.

2017-06-28 09:59 UTC, merged