Traduction de `caching.md`
vuejs-fr/vue-ssr-docs pull request #18
Opened 2017-07-17 08:01 UTC by Haeresis

Et une page de cache traduite !

2017-07-21 15:59 UTC, Haeresis commented
Dernières reviews pour boucler la trad SSR @Kocal et @forresst, on y est presque !

2017-07-22 08:27 UTC, Kocal requested changes

2017-07-22 08:27 UTC, Kocal commented on en/caching.md
> +Une application de rendu côté serveur est, dans la plupart des cas, liée a des données externes. Donc le contenu est dynamique par nature et ne peut pas être mis en cache pour des périodes étendues.
> qu'une même URL

2017-07-22 08:27 UTC, Kocal commented on en/caching.md
> +La mise en cache de composant doit donc être utilisée avec soin pour éviter les goulets d'étranglement de performance. Dans la plupart des cas, vous n'en aurez pas besoin et donc pas besoin de mettre
> les goulets d'étranglement

Tiens ? J'ai toujours dis `les goulots d'étranglement`, je pensais pas qu'il existant une alternative ^^

2017-07-22 08:40 UTC, Haeresis commented on en/caching.md
> +La mise en cache de composant doit donc être utilisée avec soin pour éviter les goulets d'étranglement de performance. Dans la plupart des cas, vous n'en aurez pas besoin et donc pas besoin de mettre
Je vais mettre goulots, j'ai plus l'habitude aussi.

2017-07-22 08:40 UTC, Haeresis commented on en/caching.md
> +Une application de rendu côté serveur est, dans la plupart des cas, liée a des données externes. Donc le contenu est dynamique par nature et ne peut pas être mis en cache pour des périodes étendues.
Provient de l’anglais uniform resource locator, littéralement « localisateur uniforme de ressource ».

On devrait donc dire « un » URL. URL \y.ɛ.ʁ‿ɛl\ masculin ou féminin (l’usage hésite) invariable, sigle.

https://fr.wiktionary.org/wiki/URL

Donc jamais de s « des URL » et un ou une est accepté. Je met un dans toutes les docs vu car ça me semble plus cohérent.

Un URL
La SEO
Une SPA

Mais ce n'est qu'un choix :)

2017-07-22 08:40 UTC, Haeresis commented
Si c'est bon pour toi, c'est bon pour moi :)

2017-07-22 08:57 UTC, Kocal approved these changes

2017-07-22 08:58 UTC, Kocal commented on en/caching.md
> +Une application de rendu côté serveur est, dans la plupart des cas, liée a des données externes. Donc le contenu est dynamique par nature et ne peut pas être mis en cache pour des périodes étendues.
Oh, j'ai toujours vu écrit `une URL` pourtant, tant pis ^^

2017-07-22 09:03 UTC, merged