Traduction de `streaming.md`
vuejs-fr/vue-ssr-docs pull request #19
Opened 2017-07-17 09:19 UTC by Haeresis

Et encore un fichier traduit :)

2017-07-21 15:59 UTC, Haeresis commented
Dernières reviews pour boucler la trad SSR @Kocal et @forresst, on y est presque !

2017-07-22 07:31 UTC, Kocal requested changes

2017-07-22 07:31 UTC, Kocal commented on en/streaming.md
> +En mode de rendu par flux, la donnée est émise aussitôt que possible quand le moteur parcours l'arbre du DOM virtuel. Cela signifie que l'envoi au client du « premier fragment » commence rapidement.
> quand le moteur parcourt

2017-07-22 07:31 UTC, Kocal commented on en/streaming.md
> +Cependant, quand le premier fragment est émis, les composants enfants peuvent ne pas avoir encore été instanciés, ni même leur cycle de vie appelé. Cela signifie que si des composants enfants on beso
Je propose de remplacer 
> ni même leur cycle de vie appelé

par 

> et les hooks de leur cycle de vie ne seront jamais appelés.

2017-07-22 07:33 UTC, Haeresis commented
T'es un chef @Kocal, je relis ça.

2017-07-22 07:48 UTC, Haeresis commented
Bon pour moi @Kocal. Merci.

2017-07-22 08:28 UTC, Kocal approved these changes

2017-07-22 08:29 UTC, merged

2017-07-22 08:29 UTC, Haeresis commented
Top