Traduction de `api.md`
vuejs-fr/vue-ssr-docs pull request #20
Opened 2017-07-17 13:25 UTC by Haeresis

2017-07-21 15:59 UTC, Haeresis commented
Dernières reviews pour boucler la trad SSR @Kocal et @forresst, on y est presque !

2017-07-22 09:52 UTC, Kocal requested changes

2017-07-22 09:52 UTC, Kocal commented on en/api.md
> +- Un chemin absolue pour générer un fichier de paquetage (`.js` ou `.json`). Doit commencer par `/` pour être considéré comme un chemin de fichier.
> Un chemin absolu

2017-07-22 09:52 UTC, Kocal commented on en/api.md
> +  Faire le rendu d'une instance de Vue sous forme de chaîne de caractères. L'objet de contexte est optionnel. La fonction de rappel est une fonction de rappel typique de Node.js avec en premier argum
> Fait le rendu

2017-07-22 09:52 UTC, Kocal commented on en/api.md
> +  Faire le rendu d'une instance de Vue sous forme de flux. L'objet de contexte est optionnel. Voir l'[Envoi par flux](./streaming.md) pour plus de détails.
> Fait le rendu

2017-07-22 09:52 UTC, Kocal commented on en/api.md
> +  Faire le rendu d'un paquetage sous forme de chaîne de caractères. L'objet de contexte est optionnel. La fonction de rappel est une fonction de rappel typique de Node.js avec en premier argument l'e
> Fait le rendu

2017-07-22 09:52 UTC, Kocal commented on en/api.md
> +  Faire le rendu d'un paquetage sous forme de flux. L'objet de contexte est optionnel. Voir l'[Envoi par flux](./streaming.md) pour plus de détails.
> Fait le rendu

2017-07-22 09:52 UTC, Kocal commented on en/api.md
> +  - [Injection manuel des fichiers](./build-config.md#injection-manuel-des-fichiers)
>Injection manuelle des fichiers

Qui devra aussi être corrigé dans le fichier `build-config.md`

2017-07-22 10:17 UTC, Haeresis commented
Je te laisse valiser ça @Kocal.

C'est top !

2017-07-22 13:58 UTC, Kocal approved these changes

2017-07-22 13:58 UTC, merged