Traduction de `non-node.md`
vuejs-fr/vue-ssr-docs pull request #22
Opened 2017-10-16 14:46 UTC by Haeresis

Une nouvelle traduction à faire !

Il y a quelque ajustement à revoir sur ce commit si vous voulez y jeter un œil : 
— https://github.com/vuejs-fr/vue-ssr-docs/commit/bb8fb6f79e4959d6636c7708f09d7d11f20d6686

2017-10-16 15:27 UTC, rspt approved these changes

2017-10-16 16:18 UTC, rspt requested changes

2017-10-16 16:18 UTC, rspt commented on en/api.md
>    Render a Vue instance to a [Node.js readble stream](https://nodejs.org/dist/latest-v8.x/docs/api/stream.html#stream_readable_streams). The context object is optional. See [Streaming](./streaming.md
Toujours en anglais?

2017-10-16 16:18 UTC, rspt commented on en/api.md
> +  Par défaut, toutes les ressources sont des morceaux asynchrones qui vont être prérécupérés du fait que se sont des directives de basse priorité. Cependant vous pouvez personnaliser c qui est préréc
"ce qui est prérécupéré"

2017-10-16 17:00 UTC, Haeresis commented
Merci @rspt. Je devrais avoir réparé ce fichu api.md pour de bon

2017-10-16 20:22 UTC, Yaty approved these changes

2017-10-16 21:07 UTC, rspt commented on en/api.md
> +- #### `renderer.renderToStream(vm[, context]): stream.Readable`
@Haeresis Pour moi c'est à double ces lignes non? ^^

2017-10-17 11:09 UTC, Haeresis commented
Bon pour toi @rspt ?

2017-10-17 11:43 UTC, rspt commented
@Haeresis Pour moi les lignes 39-41 et 43-45 sont les mêmes dans le fichier en/api.md

2017-10-17 12:07 UTC, Haeresis commented
Effectivement, c'est mieux

2017-10-17 12:12 UTC, rspt approved these changes

2017-10-17 12:17 UTC, merged

2017-10-31 07:01 UTC, forresst reviewed
Désolé j'arrive après la bataille, mais j'ai trouvé quelques erreurs ou remarques

2017-10-31 07:01 UTC, forresst commented on en/api.md
> +    Dans la 2.5.0+, les scripts injectés sont automatiquement retiré en mode production.
sont automatiquement retiré => sont automatiquement retirés

2017-10-31 07:01 UTC, forresst commented on en/api.md
> +  En plus, quand `clientManifest` est fourni, le modèle de page injecte automatiquement les éléments suivants :
modèle de page => template
> Je croyais qu'on devait garder "template" ?

2017-10-31 07:01 UTC, forresst commented on en/api.md
> +  Une fonction pour contrôler quels fichiers devraient avoir l'indice de ressource `<link rel="prefetch">` généré.
avoir l'indice de ressource `<link rel="prefetch">` généré. => avoir les cibles de la ressource `<link rel="prefetch">` générés.
> Dans MDN on parle de [cibles](https://developer.mozilla.org/fr/docs/FAQ_sur_le_pr%C3%A9chargement_des_liens#Quelles_sont_les_cibles_.C3.A0__pr.C3.A9charger_.3F) (traduction de hints). De plus hints est au pluriel, donc plusieurs.

2017-10-31 07:01 UTC, forresst commented on en/api.md
> +  Par défaut, toutes les ressources sont des morceaux asynchrones qui vont être préchargés du fait que se sont des directives de basse priorité. Cependant vous pouvez personnaliser ce qui est préchar
préchargés => préchargées
> je mettrais au féminin pluriel : on parle des "ressources" (même si c'est des "morceaux")

2017-10-31 08:50 UTC, Haeresis commented
> je croyais qu'on devait garder "template"

C'est bien le cas, mais ici on ne parle pas d'un template HTML de composant Vue. On parle de ça : 

— https://ssr.vuejs.org/fr/basic.html#utiliser-un-modèle-de-page

2017-10-31 08:54 UTC, Haeresis commented
Merci, c'est tout réajusté !

2017-10-31 09:02 UTC, forresst commented
Merci pour tes corrections et explications

2017-10-31 09:11 UTC, Haeresis commented
Merci à toi surtout !