Traduction de `routing.md`
vuejs-fr/vue-ssr-docs pull request #4
Opened 2017-05-05 18:44 UTC by Kocal

Comme dit sur le gitter, je rajoute le fichier `routing.md` que j'avais déjà traduit il y a quelque temps.
J'en ai aussi profité pour corriger quelques erreurs de traduction ou alors de tournure de phrase.

De plus, il y a quelques traductions de termes pour lesquelles je bloque, ou alors que je ne suis pas satisfait (comme @Haeresis l'a aussi dit sur gitter, on ferra sûrement une issue pour recueillir et décider des traductions de termes particuliers) : 
- `route hooks` => `connecteurs de routes`
- `resolve` => `résoudre`, est-ce qu'on laisse `resolve` ?
- `bundle` => `bundle`, est-ce qu'on utilise `paquet` ?
- `lazy-loading part` => `parties lazy-loadées`
- `as a first-class concept` => `concept de first-class`

2017-05-06 06:29 UTC, Haeresis commented
Pour resolve je garderais résoudre et rejeté (comme sylvain). Pour moi les deux idées peuvent co-exister à savoir que si la promesse est « résolue » elle est tenue.

2017-05-06 06:31 UTC, Haeresis commented
Pour bundle on peut garder bundle ou mettre paquet aussi. Mais autant empaqueter est très clair pour dire qu'on a fait un bundle, autant « paquet » peut toujours être mal interprété comme « chunck » (que nous ne traduisons par « fragment » dans Vue).

2017-05-06 06:33 UTC, Haeresis commented
Concept de première classe est tout a fait correct.

Que tu gardes first-class ou première classe ça n'avancera pas plus celui qui ne connaît pas le terme donc tu peux le traduire d'autant que la traduction existe. Si tu veux tu peux toujours laisser (*first-class*) juste après.

2017-05-06 07:50 UTC, MachinisteWeb requested changes
Good job !!

Quelques modifications proposées, je te laisse voir ça.

2017-05-06 07:50 UTC, Haeresis commented on en/SUMMARY.md
> +- [Routage et fragmentation](routing.md)
Je viens de voir que nous avions utilisé : « scission de code » pour code-splitting. Je pense que c'est bien mieux.

2017-05-06 07:50 UTC, Haeresis commented on en/routing.md
> +# Routage et fragmentation
Routage et scission de code

2017-05-06 07:50 UTC, Haeresis commented on en/routing.md
> +Vous avez sans doute remarqué que notre code serveur utilise le handler `*` qui accepte n'importe quelle URL. Cela nous permet de ré-utiliser la même configuration des routes pour le client et le ser
Je propose de traduire *handler* par **motif** (ou par symbole : http://www.expreg.com/symbole.php)

> notre code serveur utilise le motif `*` qui représente n'importe quelle URL.

Le plus juste serait « symbole » car « * » est un symbole mais les symboles servent a créer des motifs et un symbole seul peut être un motif. Après le « * » des expressions de route n'est pas exactement le même que le « * » des expressions régulière.

Ça se tiens ?

2017-05-06 07:50 UTC, Haeresis commented on en/routing.md
> +    // injection du routeur dans l'instance de Vue
> injecte le routeur dans l'instance de Vue

car tu utilises `crée` et `retourne` sinon tu aurais mis « création » et « retour ».

2017-05-06 07:50 UTC, Haeresis commented on en/routing.md
> +  // vu qu'il peut potentiellement avoir des composants ou des hooks
Pour ma part j'ai mis « point d'ancrage (*hook*) » dans les deux fichiers README.md et basic.md traductions. On a garder « hook » dans la traduction initiale de Vue mais je trouve pas que ce terme soit connu aussi bien en français que ne pourrait l'être « streaming » par exemple. Aussi j'envisagerai bien de répercuter ce terme partout à l'avenir.

Qu'en penses tu ?

2017-05-06 07:50 UTC, Haeresis commented on en/routing.md
> +  // de routes asynchrones, on retourne une Promise de telle sorte que
Dans le fichier https://github.com/vuejs-fr/vuejs.org/blob/master/src/v2/guide/components.md on a mis « une Promesse (« Promise »). Beaucoup de blog parle des Promesses etc. On peut traduire je pense. 

> de routes asynchrones, on retourne une Promesse (« Promise ») de telle sorte que

Si on ne traduit pas alors plutôt mettre entre ` pour signifier qu'on parle de l'objet tel qu'il est nommé.

> de routes asynchrones, on retourne une `Promise` de telle sorte que

2017-05-06 07:50 UTC, Haeresis commented on en/routing.md
> +    // on attend que le routeur ait terminé de traiter avec les composants et
> on attend que le routeur ait résolu les composants et points d'ancrage asynchrones

(ou hooks)

2017-05-06 07:50 UTC, Haeresis commented on en/routing.md
> +      // la Promise doit résoudre l'instance de l'application, qui pourra
> la Promesse devrait résoudre l'instance de l'application qui pourra

J'arrive à comprendre l'utilisation de la virgule, mais elle n'est pas nécessaire comme en anglais. La phrase est assez courte.

2017-05-06 07:50 UTC, Haeresis commented on en/routing.md
>  })
> Page non trouvée

> Erreur interne du serveur

2017-05-06 07:50 UTC, Haeresis commented on en/routing.md
> +## Fragmentation du code
Scission de code

2017-05-06 07:50 UTC, Haeresis commented on en/routing.md
> +La fragmentation du code, ou les parties chargées à la volée de votre application, aide à réduire la quantité de ressources qui a besoin d'être téléchargée par le navigateur pour le rendu initial, et
> La scission du code

2017-05-06 07:50 UTC, Haeresis commented on en/routing.md
> +La fragmentation du code, ou les parties chargées à la volée de votre application, aide à réduire la quantité de ressources qui a besoin d'être téléchargée par le navigateur pour le rendu initial, et
> Le but est de « charger uniquement ce qui est nécessaire »

Avec les guillemets français.

2017-05-06 07:50 UTC, Haeresis commented on en/routing.md
> +Vue permet de créer des composants asynchrones en respectant le concept d'[objet de première classe](https://fr.wikipedia.org/wiki/Objet_de_premi%C3%A8re_classe). En les combinant avec [le support de
> pour scinder le code

(on va réserver le terme fragment et fragmenter pour les « chunk »)

2017-05-06 07:50 UTC, Haeresis commented on en/routing.md
> +Cela fonctionnera dans n'importe quel scénario si vous êtes en train de faire une application Vue uniquement pour le côté client. Toutefois, il y aura certaines limitations en l'utilisant dans du SSR
> en l'utilisant avec du SSR

« dans » donne l'impression que le SSR est une chose alors que c'est plutôt un concept

2017-05-06 08:35 UTC, Kocal commented on en/SUMMARY.md
> +- [Routage et fragmentation](routing.md)
Fixé dans c55d5d4.

2017-05-06 08:36 UTC, Kocal commented on en/routing.md
> +# Routage et fragmentation
Fixé dans c55d5d4.

2017-05-06 08:37 UTC, Kocal commented on en/routing.md
> +Vous avez sans doute remarqué que notre code serveur utilise le handler `*` qui accepte n'importe quelle URL. Cela nous permet de ré-utiliser la même configuration des routes pour le client et le ser
Je pense que **motif** est une bonne traduction pour *handler*.
Est-ce que je modifie la traduction tout de suite ou on attend 2/3 avis ?

2017-05-06 08:37 UTC, Kocal commented on en/routing.md
> +## Fragmentation du code
Fixé dans c55d5d4.

2017-05-06 08:37 UTC, Kocal commented on en/routing.md
> +Vue permet de créer des composants asynchrones en respectant le concept d'[objet de première classe](https://fr.wikipedia.org/wiki/Objet_de_premi%C3%A8re_classe). En les combinant avec [le support de
Fixé dans c55d5d4.

2017-05-06 08:39 UTC, Kocal commented on en/routing.md
> +La fragmentation du code, ou les parties chargées à la volée de votre application, aide à réduire la quantité de ressources qui a besoin d'être téléchargée par le navigateur pour le rendu initial, et
Fixé dans c55d5d4 et dans 6ef2962.

2017-05-06 09:37 UTC, Kocal commented on en/routing.md
>  })
Fixé dans eaf52d1.

2017-05-06 09:37 UTC, Kocal commented on en/routing.md
> +Cela fonctionnera dans n'importe quel scénario si vous êtes en train de faire une application Vue uniquement pour le côté client. Toutefois, il y aura certaines limitations en l'utilisant dans du SSR
Fixé dans eaf52d1.

2017-05-06 09:37 UTC, Kocal commented on en/routing.md
> +      // la Promise doit résoudre l'instance de l'application, qui pourra
Fixé dans eaf52d1.

2017-05-06 09:37 UTC, Kocal commented on en/routing.md
> +  // de routes asynchrones, on retourne une Promise de telle sorte que
Fixé dans eaf52d1.

2017-05-06 09:39 UTC, Kocal commented on en/routing.md
> +    // injection du routeur dans l'instance de Vue
Fixé dans b95edcd.

2017-05-06 09:40 UTC, Kocal commented
Je viens d'apporter des modifications par rapport à tes reviews.
Il y a cependant la traduction de `hook` qui reste en suspend.

2017-05-06 12:42 UTC, MachinisteWeb approved these changes

2017-05-06 12:43 UTC, Haeresis commented on en/routing.md
> +  // vu qu'il peut potentiellement avoir des composants ou des hooks
Ok. @sylvainpolletvillard était déjà de cet avis. J'ai mis hook aussi de mon côté.

2017-05-06 12:44 UTC, Haeresis commented on en/routing.md
> +Vous avez sans doute remarqué que notre code serveur utilise le handler `*` qui accepte n'importe quelle URL. Cela nous permet de ré-utiliser la même configuration des routes pour le client et le ser
On va attendre de voir ce qu'en pense @sylvainpolletvillard.

2017-05-06 23:43 UTC, sylvainpolletvillard commented on en/routing.md
> +Vous avez sans doute remarqué que notre code serveur utilise le handler `*` qui accepte n'importe quelle URL. Cela nous permet de ré-utiliser la même configuration des routes pour le client et le ser
Une traduction plus littérale serait "gestionnaire", mais dans ce contexte "motif" ou "caractère spécial" est plus clair.

2017-05-06 23:45 UTC, sylvainpolletvillard commented on en/routing.md
> +  // vu qu'il peut potentiellement avoir des composants ou des hooks
En cas de doute, mettre les deux est toujours une bonne idée. Le terme d'origine en premier et la traduction entre parenthèses derrière, comme ça on peut réutiliser le terme dans la suite du document sans avoir à le réexpliquer.

2017-05-07 12:59 UTC, Kocal commented on en/routing.md
> +  // vu qu'il peut potentiellement avoir des composants ou des hooks
Donc finalement est-ce qu'on garde `hook` ? https://github.com/vuejs-fr/vuejs.org/issues/4#issuecomment-271571663

2017-05-07 13:15 UTC, sylvainpolletvillard commented on en/routing.md
> +  // vu qu'il peut potentiellement avoir des composants ou des hooks
oui mais si tu trouves que ce n'est pas assez clair, tu peux ajouter `(point d'ancrage)` derrière. Mieux vaut en dire trop que pas assez.

2017-05-08 14:03 UTC, Haeresis commented
Pour moi dans l'état actuel c'est bon, on ferra des PRs pour les fautes d'ortho plus tard quand on aura plus de traducteur sur le projet.

Tu peux merger je pense

2017-05-08 14:04 UTC, merged