Traduction de universal & structure
vuejs-fr/vue-ssr-docs pull request #5
Opened 2017-05-10 14:00 UTC by mdartic

Merci de relire ces deux traductions,

J'ai fait au mieux et me suis inspiré de ce que j'ai pu voir dans les traductions déjà existantes, et d'une issue répertoriant des conseils de traduction.

J'ai traduit les commentaires de code, et les libellés présents dedans, mais n'ai pas renommé les variables.

2017-05-10 15:17 UTC, MachinisteWeb requested changes
Top ! Merci pour ta contribution @mdartic !

Voici mes retour !

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +Comme vu dans l'exemple de base, nous **créons une nouvelle instance racine Vue pour chaque requête.** Cela est similaire au fait que chaque utilisateur utilise une nouvelle instance de l'application
Je le proposerai plutôt dans cet ordre pour garder « l'instance **de** Vue »

> instance de Vue racine

ou 

> instance de Vue principale 

je propose

> d'une pollution d'état entre requête

ou

> d'une pollution d'état inter-requête

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +Ainsi, au lieu de créer directement une instance d'application, nous devons exposer une fonction Fabrique qui peut être exécutée à plusieurs reprises pour créer de nouvelles instances d'application p
> fonction de fabrique

de la même manière que declaration function se traduit par déclaration de fonction ou expression function par fonction d'expression je pense que l'on peut dire que factory function devient très simplement fonction de fabrique

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +    template: `<div>L'URL visible est: {{ url }}</div>`
> est :

espace entre `est` et `:`

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +Et notre code serveur devient:
> devient : 

(espace)

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +La même règle s'applique aussi bien au routeur, qu'au store et aux instances de bus d'événements. Au lieu de l'exporter directement depuis un module et de l'importer dans votre application, vous deve
> instance racine de Vue 

à aligner avec se qui aura été choisi pour "l'instance racine Vue" discuté plus haut

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +> Cette contrainte peut être éliminée en utilisant le bundle renderer avec `{ runInNewContext: true}`, cependant il y aura un surcoût significatif en terme de performance lié à la création d'un nouve
un espace entre `true` et `}`

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +> Cette contrainte peut être éliminée en utilisant le bundle renderer avec `{ runInNewContext: true}`, cependant il y aura un surcoût significatif en terme de performance lié à la création d'un nouve
je traduirais `bundle renderer` par 

> **moteur de rendu empaqueté (« bundle renderer »)** 

ou

> **moteur de rendu pré-compilé (« bundle renderer »)** 

ou

> **moteur de rendu pré-conçu (« bundle renderer »)** 

et continuerai avec ce terme ensuite car nous avons toujours traduit renderer par moteur de rendu et le terme bundle veut juste dire que ça a été « pré-packagé » que c'est prèt à l'emploi dans un petit paquet tout propre :)

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +Jusqu'ici, nous n'avons pas encore discuté d'une méthode livraison pour disposer de la même application Vue côté client. Pour cela, nous devons utiliser webpack pour fabriquer le bundle de notre appl
retirer « livraison », disposer remplace très bien délivrer dans ce contexte.

Sinon plutôt rajouter un *de*

> Jusqu'ici, nous n'avons pas encore discuté d'une méthode **de** livraison

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +Jusqu'ici, nous n'avons pas encore discuté d'une méthode livraison pour disposer de la même application Vue côté client. Pour cela, nous devons utiliser webpack pour fabriquer le bundle de notre appl
> le bundle serveur

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +- les applications typiques Vue sont construites avec webpack et `vue-loader`, et beaucoup d'autres fonctionnalités spécifiques à webpack telles que l'import de fichiers via `file-loader`, ou encore
> Les

(majuscule)

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +L'idée de base est donc que nous utiliserons webpack pour empaqueter notre application à la fois pour le client et le serveur - le bundle serveur sera nécessaire au serveur et utilisé pour le rendu c
Je pense que 

> pour hydrater le DOM client.

ou 

> pour hydrater les balises clientes.

est une traduction correcte plus parlante

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +Nous allons discuter des détails du setup dans les prochaines sections - pour l'instant, considérons que nous avons configuré le build et que nous pouvons écrire le code de notre application Vue avec
> des détails de la mise en place dans les prochaines sections. Pour l'instant

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +Maintenant que nous utilisons webpack pour développer l'application à la fois côté serveur et client, la majorité de notre code source peut être écrite d'une manière universelle, avec l'accès à toute
Je pense que « both » demande la répétition des termes

> côté serveur et côté client

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +`app.js` est l'entrée universelle de notre application. Dans une application exclusivement client, nous aurions créé l'instance racine Vue directement dans ce fichier, et elle aurait été attachée au
> exclusivement cliente

> instance **de** Vue racine

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +// exporte une fonction Fabrique pour créer de nouvelles instances
> fonction de fabrique

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +L'entrée client crée simplement l'application et l'attache au DOM:
> L'entrée cliente

> au DOM : 

(espace entre `DOM` et `:`)

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +// logique de bootstrap spécifique client
> // logique spécifique cliente de démarrage...

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +// nous partons du principe que l'élément racine du template App.vue a pour id="app"
> nous partons du principe que l'élément racine du template App.vue est `id="app"`

avec les ` autour des partie de code

Je vais faire une PR pour l'ajout des « ` » à l'originale

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +L'entrée serveur utilise un export par défaut qui est une fonction pouvant être appelée de manière répétée à chaque rendu. Pour l'instant, le code ne fait pas grand chose de plus que créer et retourn
Remplacer « — » par« ; » ou par « . » plus courant en français (dans le dernier cas penser à la majuscule)

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
> +L'entrée serveur utilise un export par défaut qui est une fonction pouvant être appelée de manière répétée à chaque rendu. Pour l'instant, le code ne fait pas grand chose de plus que créer et retourn
> pré-chargement

je crois

2017-05-10 15:17 UTC, MachinisteWeb commented on en/structure.md
>  # Structure de code (En) <br><br> *Cette page est en cours de traduction française. Revenez une autre fois pour lire une traduction achevée ou [participez à la traduction française ici](https://githu
Supprimer le (EN) et toute la suite

2017-05-10 15:17 UTC, MachinisteWeb commented on en/universal.md
>  # Écrire du code universel (En) <br><br> *Cette page est en cours de traduction française. Revenez une autre fois pour lire une traduction achevée ou [participez à la traduction française ici](https:
Supprimer le (EN) et toute la suite

2017-05-10 15:17 UTC, MachinisteWeb commented on en/universal.md
> +Avant d'aller plus loin, prenons un moment pour discuter des contraintes lorsque l'on écrit du code "universel" - c'est à dire du code qui s'exécute à la fois côté serveur et côté client. En raison d
> « universel », c'est à dire,

2017-05-10 15:17 UTC, MachinisteWeb commented on en/universal.md
> +Avant d'aller plus loin, prenons un moment pour discuter des contraintes lorsque l'on écrit du code "universel" - c'est à dire du code qui s'exécute à la fois côté serveur et côté client. En raison d
> d'API entre les deux plateformes

2017-05-10 15:17 UTC, MachinisteWeb commented on en/universal.md
> +Dans une application qui tourne exclusivement côté client, chaque utilisateur utilisera une nouvelle instance de l'application dans leur navigateur. Pour le rendu serveur nous voulons le même fonctio
> fonctionnement : 

(espace)

> une nouvelle instance d’application isolée

> partage d'état entre requête

ou

> partage d'état inter-requête

2017-05-10 15:17 UTC, Haeresis commented on en/universal.md
> +Etant donné que le processus de rendu actuel doit être déterministe, nous allons aussi "pré-charger" les données sur le serveur - cela signifie que l'état de notre application sera déjà disponible qu
> « pré-charger »

> sur le serveur. Cela signifie

> le rendu. Cela signifie également que

(car la répétition est mal vu en français)

Pour plus de fluidité je mettrais

> est inutile côté serveur ; elle est donc désactivée par défaut

2017-05-10 15:17 UTC, Haeresis commented on en/universal.md
> +Etant donné que le processus de rendu actuel doit être déterministe, nous allons aussi "pré-charger" les données sur le serveur - cela signifie que l'état de notre application sera déjà disponible qu
Pour faire respirer le texte je mettrais

> côté serveur ; elle est donc désactivée par défaut.

> le coût de performance d'une conversion de données en objets réactifs

(ouais pas mal de « de »)

2017-05-10 15:17 UTC, Haeresis commented on en/universal.md
> +Vu qu'il n'y a pas de mises à jour dynamiques, de tous les connecteurs de cycles de vie, seuls `beforeCreate` et `created` seront appelés pendant le rendu côté serveur. Cela signifie que tout code pr
remettre hook au lieu de connecteurs et proposer une traduction général de hook par connecteur sur vue-fr/vuejs.org dans les issues (connecteurs c'est pas mal ! Moi je préfère toujours point d'ancrage haha).

2017-05-10 15:17 UTC, Haeresis commented on en/universal.md
> +## Accès aux APIs spécifique à la plate-forme
> spécifiques

> plateforme

2017-05-10 15:17 UTC, Haeresis commented on en/universal.md
> +Le code universel ne peut pas accéder aux APIs spécifiques à une plate-forme. Ainsi, si votre code utilise directement les variables globales exclusives au navigateur comme `window` ou `document`, el
> plateforme https://fr.wikipedia.org/wiki/Rectifications_orthographiques_du_fran%C3%A7ais_en_1990

2017-05-10 15:17 UTC, Haeresis commented on en/universal.md
> +Pour les tâches partagées entre le serveur et le client, mais qui utilisent des APIs différentes selon la plate-forme, il est recommandé d'encapsuler le code spécifique à la plate-forme dans une API
> plateforme

> plateforme

> côté serveur et côté client

2017-05-10 15:17 UTC, Haeresis commented on en/universal.md
> +Pour les APIs exclusives au navigateur, l'approche habituelle est de les utiliser dans les connecteurs de cycle de vie exclusifs au client.
conserver hook au lieu de connecteur

2017-05-10 15:17 UTC, Haeresis commented on en/universal.md
> +Notez que si une bibliothèque tierce n'est pas écrite avec l'objectif d'être universelle, cela peut être délicat de l'intégrer dans une application rendue côté serveur. Vous *devriez* être capable de
> avec du code de détection d'environnement des autres bibliothèques

2017-05-10 15:17 UTC, Haeresis commented on en/universal.md
> +2. Si vous avez une directive personnalisée qui ne peut être facilement remplacée par des composants, vous pouvez en fournir une "version serveur" qui utilise l'option [`directives`](./api.md#directi
> « version serveur »

2017-05-10 15:17 UTC, Haeresis commented on en/structure.md
> +## Eviter les singletons stateful
Je pense que l'on peut traduire cet full par état

Par exemple « Stateful Firewall » se traduit par « pare-feu d'état » https://fr.wikipedia.org/wiki/Pare-feu_%C3%A0_%C3%A9tats

2017-05-11 06:54 UTC, Kocal requested changes
Merci pour la contribution !

2017-05-11 06:54 UTC, Kocal commented on en/structure.md
> +Lors de l'écriture du code exclusif au client, nous sommes habitués au fait que notre code sera interprété dans un nouveau contexte à chaque fois. Cependant, un serveur Node.js est un processus au lo
>un serveur Node.js est un processus au long cours 

Pour ma part, lorsque j'avais commencé à traduire vue-ssr-docs de mon côté (https://github.com/vuejs/vue-ssr-docs/pull/5), j'avais utilisé la formulation : `un serveur Node.js est un processus qui reste actif dans le temps`.
Qu'en penses-tu ?

2017-05-11 06:54 UTC, Kocal commented on en/structure.md
> +Comme vu dans l'exemple de base, nous **créons une nouvelle instance racine Vue pour chaque requête.** Cela est similaire au fait que chaque utilisateur utilise une nouvelle instance de l'application
+1 pour `l'instance de Vue`.

2017-05-11 06:54 UTC, Kocal commented on en/structure.md
>  So, instead of directly creating an app instance, we should expose a factory function that can be repeatedly executed to create fresh app instances for each request:
Il faut aussi penser à supprimer le paragraphe original :stuck_out_tongue:

2017-05-11 06:54 UTC, Kocal commented on en/structure.md
> +La même règle s'applique aussi bien au routeur, qu'au store et aux instances de bus d'événements. Au lieu de l'exporter directement depuis un module et de l'importer dans votre application, vous deve
> store

Est-ce qu'on n'avait pas traduit ce terme pour `gestionnaire d'état` dans la doc de vue-router ?

2017-05-11 06:54 UTC, Kocal commented on en/structure.md
> +- les applications typiques Vue sont construites avec webpack et `vue-loader`, et beaucoup d'autres fonctionnalités spécifiques à webpack telles que l'import de fichiers via `file-loader`, ou encore
> qui ne **fonctionneraient** pas

2017-05-11 06:54 UTC, Kocal commented on en/universal.md
> +Dans une application qui tourne exclusivement côté client, chaque utilisateur utilisera une nouvelle instance de l'application dans leur navigateur. Pour le rendu serveur nous voulons le même fonctio
Remplacer `d'une nouvelle instance d'application, et isolée` pour `d'une nouvelle instance d'application isolée` ?

2017-05-11 07:02 UTC, Haeresis commented on en/structure.md
> +Lors de l'écriture du code exclusif au client, nous sommes habitués au fait que notre code sera interprété dans un nouveau contexte à chaque fois. Cependant, un serveur Node.js est un processus au lo
J'avais également butté sur la formulation. J'ai été me renseigné et c'est quelque chose qui se dit quand un phénomène dure dans le temps.

C'est pas mal ce mot « actif », c'est la clé.

> un processus qui reste actif

tout simplement représente bien un long-running processus (en gros un processus qui se clos pas à la fin des instructions).

Donc si c'est bon pour vous deux j'ajouterai bien au liste des termes à traduire par ceci

**long-running process** = processus qui reste actif

2017-05-11 07:05 UTC, Kocal commented on en/structure.md
> +Lors de l'écriture du code exclusif au client, nous sommes habitués au fait que notre code sera interprété dans un nouveau contexte à chaque fois. Cependant, un serveur Node.js est un processus au lo
Pour moi ça me va :+1:

2017-05-11 07:09 UTC, Haeresis commented on en/structure.md
> +La même règle s'applique aussi bien au routeur, qu'au store et aux instances de bus d'événements. Au lieu de l'exporter directement depuis un module et de l'importer dans votre application, vous deve
Justement je demandais dans les pages traduite avant si on gardait pas le terme « store ». Je pense le garder en attendant de réellement comprendre toute sa portée et lui trouver un équivalent en un seul mot car toute les traduction de store me semble pas approprié.

2017-05-13 21:05 UTC, mdartic commented on en/structure.md
> +> Cette contrainte peut être éliminée en utilisant le bundle renderer avec `{ runInNewContext: true}`, cependant il y aura un surcoût significatif en terme de performance lié à la création d'un nouve
ok, est ce que ça vaut le coup de rajouter cette traduction dans l'ensemble des mots que l'on historise ?

2017-05-13 21:06 UTC, mdartic commented on en/structure.md
> +> Cette contrainte peut être éliminée en utilisant le bundle renderer avec `{ runInNewContext: true}`, cependant il y aura un surcoût significatif en terme de performance lié à la création d'un nouve
au fait, j'ai choisi la version moteur de rendu pré-compilé

2017-05-13 21:12 UTC, mdartic commented on en/structure.md
> +`app.js` est l'entrée universelle de notre application. Dans une application exclusivement client, nous aurions créé l'instance racine Vue directement dans ce fichier, et elle aurait été attachée au
Euh, pour 'exclusivement cliente', je ne suis pas convaincu.
A mon sens, j'entends 'client' comme le côté client / côté serveur. 
J'omets le mot 'côté', car cela fait écho aux autres paragraphes où on parle d'app client, d'app serveur, et dans ce paragraphe on est que côté client.
Qu'en penses tu ?

2017-05-13 21:19 UTC, mdartic commented on en/structure.md
> +// logique de bootstrap spécifique client
ok pour démarrage, mais même remarque que pour le paragraphe sur l'application.
pour l'instant, je laisse client
je conserve l'ordre 'logique de démarrage spécifique client', j'ai l'impression que c plus français ?

2017-05-13 21:22 UTC, mdartic commented on en/structure.md
> +// nous partons du principe que l'élément racine du template App.vue a pour id="app"
penses tu que ce soit utile sachant que nous sommes déjà dans une portion de code ?
j'ai ajouté les backquotes(backtits ?), mais ça ne le transforme pas en code, vu que nous sommes déjà dans une portion de code.

2017-05-13 21:48 UTC, mdartic commented on en/universal.md
> +Vu qu'il n'y a pas de mises à jour dynamiques, de tous les connecteurs de cycles de vie, seuls `beforeCreate` et `created` seront appelés pendant le rendu côté serveur. Cela signifie que tout code pr
j'en avais discuté vite fait sur gitter, et comme hook est admis en français, je supprime connecteur et remets hook.
wikipedia référence les [hooks](https://fr.wikipedia.org/wiki/Hook_(informatique))

2017-05-13 21:49 UTC, mdartic commented on en/universal.md
> +## Accès aux APIs spécifique à la plate-forme
pour plate-forme, les deux écritures existent, la réforme de 1990 autorise sans le tiret.
le mot apparaît ailleurs j'imagine ? je peux mettre en cohérence les mots s'il le faut.

2017-05-13 21:52 UTC, mdartic commented on en/universal.md
> +Le code universel ne peut pas accéder aux APIs spécifiques à une plate-forme. Ainsi, si votre code utilise directement les variables globales exclusives au navigateur comme `window` ou `document`, el
ah ben tiens tu as mis le lien :-)
que fait on du coup ? on le supprime ? (les deux sont exacts)

2017-05-13 21:57 UTC, Haeresis commented on en/structure.md
> +// nous partons du principe que l'élément racine du template App.vue a pour id="app"
Le Markdown  est un langage utilisé pour les documentation et les commentaires de code. Que l'outil qui transforme le Markdown en Markup le fasse ou non doit etre indépendant de la syntaxe initiale qui a pour but : "de rendre un document .txt lisible. 

id="app" n'est pas un nom propre ni un titre ni un nom de fichier, c'est un pend de code court. Les pends de code cours sont entre tick. Tu peux attendre que la PR passe si tu veux, on fera les modifications rétroactivement.

2017-05-13 22:03 UTC, mdartic commented on en/structure.md
> +// nous partons du principe que l'élément racine du template App.vue a pour id="app"
ok pour attendre, on sera cohérent par rapport à l'origine comme ça.

2017-05-13 22:05 UTC, Haeresis commented on en/structure.md
> +// logique de bootstrap spécifique client
Pour moi partie cliente me semble plus naturel. J'ai regardé rapidement ici : https://books.google.fr/books?id=IBrRCQAAQBAJ&pg=PA65&lpg=PA65&dq=la+partie+cliente&source=bl&ots=henTcxNuK4&sig=0coe037Pw_yVgeNAQrZESmQ0LjI&hl=fr&sa=X&ved=0ahUKEwijzPjN7u3TAhXHRhQKHZQPDmQQ6AEIXjAR#v=onepage&q=la%20partie%20cliente&f=false

Je ferrai une recherche plus approfondie lundi sur la doc fr.vuejs.org

Hésite pas à ouvrir une issue car tu me mets le doute puisque "une partie serveuse" ne se dit pas :) 

Voir si d'autres avis éclairé peuvent aider

2017-05-13 22:07 UTC, mdartic commented
Merci @Kocal & @Haeresis pour les revues !
J'ai pris en considération la majeure partie de vos remarques normalement.
Il reste plate-forme / plateforme, et application client / cliente.

2017-05-13 22:10 UTC, Haeresis commented on en/universal.md
> +Le code universel ne peut pas accéder aux APIs spécifiques à une plate-forme. Ainsi, si votre code utilise directement les variables globales exclusives au navigateur comme `window` ou `document`, el
On évite autant que possible les tirets. C'est un choix totalement arbitraire qu'on a validé, c'est pour la cohérence : monopage, monofichier, plateforme, etc. 

Du coup je le mentionnait :)

2017-05-13 22:13 UTC, mdartic commented on en/structure.md
> +// logique de bootstrap spécifique client
ok, cf https://github.com/vuejs-fr/vue-ssr-docs/issues/7

2017-05-13 22:15 UTC, mdartic commented on en/universal.md
> +Le code universel ne peut pas accéder aux APIs spécifiques à une plate-forme. Ainsi, si votre code utilise directement les variables globales exclusives au navigateur comme `window` ou `document`, el
ok, corrigé !

2017-05-13 22:17 UTC, Haeresis commented on en/structure.md
> +Ainsi, au lieu de créer directement une instance d'application, nous devons exposer une fonction Fabrique qui peut être exécutée à plusieurs reprises pour créer de nouvelles instances d'application p
Je me suis trompé car on dit déclaration de fonction et expression de fonction. 

P-e que fabrique de fonction est plus juste ?

2017-05-13 22:21 UTC, mdartic commented on en/structure.md
> +Ainsi, au lieu de créer directement une instance d'application, nous devons exposer une fonction Fabrique qui peut être exécutée à plusieurs reprises pour créer de nouvelles instances d'application p
ah, ma référence était https://fr.wikipedia.org/wiki/Fabrique_(patron_de_conception)
on utilise plutôt méthode de fabrique dans l'explication, du coup, fonction de fabrique me paraissait bien ?

2017-05-13 22:26 UTC, Haeresis commented
Non c'est bien ! C'était au cas ou. Je crois que @sylvainpolletvillard a
déjà utilisé le terme fonction de fabrique

Envoyé depuis mon Smartphone. Excusez-moi d'être bref.

Le 14 mai 2017 00:21, "Mathieu DARTIGUES" <notifications@github.com> a
écrit :

> *@mdartic* commented on this pull request.
> ------------------------------
>
> In en/structure.md
> <https://github.com/vuejs-fr/vue-ssr-docs/pull/5#discussion_r116368339>:
>
> >
>  So, instead of directly creating an app instance, we should expose a factory function that can be repeatedly executed to create fresh app instances for each request:
>
> +Ainsi, au lieu de créer directement une instance d'application, nous devons exposer une fonction Fabrique qui peut être exécutée à plusieurs reprises pour créer de nouvelles instances d'application pour chaque requête :
>
> ah, ma référence était https://fr.wikipedia.org/wiki/Fabrique_(patron_de_
> conception)
> on utilise plutôt méthode de fabrique dans l'explication, du coup,
> fonction de fabrique me paraissait bien ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/vuejs-fr/vue-ssr-docs/pull/5#discussion_r116368339>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADs8ucskF_wKNlR9bVzqxEq3fhgTr0Wfks5r5izkgaJpZM4NWtQB>
> .
>

2017-05-13 22:27 UTC, Haeresis commented
Ou l'inverse :p je sais plus !

Envoyé depuis mon Smartphone. Excusez-moi d'être bref.

Le 14 mai 2017 00:26, "Bruno Lesieur" <bruno.lesieur@gmail.com> a écrit :

> Non c'est bien ! C'était au cas ou. Je crois que @sylvainpolletvillard a
> déjà utilisé le terme fonction de fabrique
>
> Envoyé depuis mon Smartphone. Excusez-moi d'être bref.
>
> Le 14 mai 2017 00:21, "Mathieu DARTIGUES" <notifications@github.com> a
> écrit :
>
>> *@mdartic* commented on this pull request.
>> ------------------------------
>>
>> In en/structure.md
>> <https://github.com/vuejs-fr/vue-ssr-docs/pull/5#discussion_r116368339>:
>>
>> >
>>  So, instead of directly creating an app instance, we should expose a factory function that can be repeatedly executed to create fresh app instances for each request:
>>
>> +Ainsi, au lieu de créer directement une instance d'application, nous devons exposer une fonction Fabrique qui peut être exécutée à plusieurs reprises pour créer de nouvelles instances d'application pour chaque requête :
>>
>> ah, ma référence était https://fr.wikipedia.org/wiki/
>> Fabrique_(patron_de_conception)
>> on utilise plutôt méthode de fabrique dans l'explication, du coup,
>> fonction de fabrique me paraissait bien ?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/vuejs-fr/vue-ssr-docs/pull/5#discussion_r116368339>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/ADs8ucskF_wKNlR9bVzqxEq3fhgTr0Wfks5r5izkgaJpZM4NWtQB>
>> .
>>
>

2017-05-13 22:40 UTC, sylvainpolletvillard commented
Pour factory function ? Oui je traduis ça en fonction fabrique: https://fr.wikipedia.org/wiki/Fabrique_(patron_de_conception)

"Fabrique de fonctions" est valable seulement si la fonction fabrique retourne effectivement une fonction (pour de la curryfication par exemple). Mais on utilise le plus souvent le terme en programmation orientée objet, où les fabriques retournent des objets instances de classes.

2017-05-14 05:38 UTC, Kocal approved these changes

2017-05-18 08:53 UTC, MachinisteWeb approved these changes

2017-05-18 08:53 UTC, merged