Starting translation of data.md
vuejs-fr/vue-ssr-docs pull request #8
Opened 2017-05-19 16:23 UTC by Haeresis

Signed-off-by: Bruno Lesieur <bruno.lesieur@gmail.com>

2017-05-20 08:27 UTC, Kocal reviewed
Merci pour la traduction, voici ma review ^^

2017-05-20 08:27 UTC, Kocal commented on en/data.md
> +Pour résoudre cela, les données pré-chargées doivent vivre en dehors de la vue du composant, dans un gestionnaire de données, ou dans un « gestionnaire d'état ». Côté serveur, nous pouvons pré-charge
> De plus, nous allons sérialiser et injecter l'état dans le HTML

2017-05-20 08:27 UTC, Kocal commented on en/data.md
> +et mettons à jour `app.js`:
> Et

2017-05-20 08:27 UTC, Kocal commented on en/data.md
> +Donc, ou devons nous appeler le code en charge de l'action de pré-chargement ?
> où

2017-05-20 08:27 UTC, Kocal commented on en/data.md
> +Les données que nous avons besoin de pré-charger sont déterminées par la route visitée, qui va aussi déterminée quel composant va être rendu. En fait, les données nécessaire a une route donnée sont a
> va aussi déterminer

> données nécessaires

> données nécessaires

2017-05-20 08:27 UTC, Kocal commented on en/data.md
> +Dans `entry-server.js` nous pouvons obtenir des composants qu'ils concordent avec une route grâce à `router.getMatchedComponents()`, et appeler `asyncData` si le composant l'expose. Nous avons ensuit
> des composants qui concordent

> l'état résolu

2017-05-20 08:27 UTC, Kocal commented on en/data.md
> +      // appeler `asyncData()` sur toutes les routes concordant
> les routes concordantes

2017-05-20 08:27 UTC, Kocal commented on en/data.md
> +        // Après que chaque hook de pré-chargement soit résolue, notre store est maintenant
> soit résolu

2017-05-20 08:27 UTC, Kocal commented on en/data.md
> +        // sérialisé et injecté dans le HTML pour alimenter window.__INITIAL_STATE__.
> être sérialisé et injecté dans le HTML en tant que window.__INITIAL_STATE__.

n'était pas bon ?

2017-05-20 08:28 UTC, Kocal requested changes
Trompé, j'ai commenté au lieu de demandé des changements..

2017-05-27 07:49 UTC, Haeresis commented
J'ai refait une relecture ici.

Il me reste un doute pour « jeu de logique », c'est bien de cela dont il est question ?

2017-05-27 09:51 UTC, Kocal commented
Pas de problème :)

Mmmh, pour `some mocked logic`, j'ai vu que `mock` pouvait se traduire en [`simulacre`](https://fr.wikipedia.org/wiki/Simulacre), et qui correspond plutôt bien à une utilisation en informatique.

Cependant, je ne vois pas trop pourquoi `some mocked logic` a été utilisé, peut-être pour la fonction `fetchItem` du fichier `api.js` (`import { fetchItem } from './api'`) ?

2017-05-27 09:51 UTC, Kocal approved these changes

2017-05-27 12:32 UTC, merged